import "@ionic/core/css/core.css";
import "@ionic/core/css/normalize.css";
import "@ionic/core/css/structure.css";
import "@ionic/core/css/typography.css";
import "@ionic/core/css/padding.css";
import "@ionic/core/css/flex-utils.css";
import "@ionic/core/css/display.css";
import "./style.css";

import { NixComponent, html, mount, nixRouter } from "@deijose/nix-js";
import {
  IonRouterOutlet,
  createBottomTabBar,
  createTabsLayout,
  NavigationManager,
} from "@deijose/nix-ionic";

// Auto-generated by the Vite plugin — scans html`` templates for <ion-*> tags
// and <ion-icon name="..."> and registers only what you use.
import "virtual:nix-ionic/registration";

import { home, homeOutline, map, mapOutline, person, personOutline } from "ionicons/icons";

import { HomePage } from "./pages/HomePage";
import { MapPage } from "./pages/MapPage";
import { ProfilePage } from "./pages/ProfilePage";
import { LoginPage } from "./pages/LoginPage";
import { RouteDetailPage } from "./pages/RouteDetailPage";
import { authStore } from "./stores/auth";

const router = nixRouter();

const nav = new NavigationManager({
  tabs: ["/", "/map", "/profile"],
});

const requireAuth = () => (authStore.isAuthenticated.value ? true : "/login");

const outlet = new IonRouterOutlet(
  [
    { path: "/login", component: (ctx) => new LoginPage(ctx) },
    { path: "/", component: (ctx) => new HomePage(ctx), beforeEnter: requireAuth },
    { path: "/map", component: (ctx) => new MapPage(ctx), beforeEnter: requireAuth },
    { path: "/map/route/:id", component: (ctx) => new RouteDetailPage(ctx), beforeEnter: requireAuth },
    { path: "/profile", component: (ctx) => new ProfilePage(ctx), beforeEnter: requireAuth },
  ],
  {
    tabs: ["/", "/map", "/profile"],
    navigation: nav,
  },
);

const tabBar = createBottomTabBar(
  [
    { path: "/", label: "Home", icon: "home-outline", activeIcon: "home", exact: true },
    { path: "/map", label: "Map", icon: "map-outline", activeIcon: "map" },
    { path: "/profile", label: "Profile", icon: "person-outline", activeIcon: "person" },
  ],
  {
    hiddenPaths: ["/login", "/map/route/*"],
    icons: { home, "home-outline": homeOutline, map, "map-outline": mapOutline, person, "person-outline": personOutline },
  },
);

const tabsLayout = createTabsLayout(outlet, tabBar);

class App extends NixComponent {
  override render() {
    return html`<ion-app>${tabsLayout}</ion-app>`;
  }
}

mount(new App(), "#app");
