import "@ionic/core/css/core.css";
import "@ionic/core/css/normalize.css";
import "@ionic/core/css/structure.css";
import "@ionic/core/css/typography.css";
import "@ionic/core/css/padding.css";
import "@ionic/core/css/flex-utils.css";
import "@ionic/core/css/display.css";
import "./style.css";

import { ElurComponent, html, mount, elurRouter } from "@elurjs/core";
import { IonRouterOutlet } from "@elurjs/ionic";

// Auto-generated by the Vite plugin — scans html`` templates for <ion-*> tags
// and <ion-icon name="..."> and registers only what you use.
import "virtual:elur-ionic/registration";

import { HomePage } from "./pages/HomePage";
import { AboutPage } from "./pages/AboutPage";

const router = elurRouter();

const outlet = new IonRouterOutlet([
  { path: "/", component: (ctx) => new HomePage(ctx) },
  { path: "/about", component: (ctx) => new AboutPage(ctx) },
]);

class App extends ElurComponent {
  override render() {
    return html`<ion-app>${outlet}</ion-app>`;
  }
}

mount(new App(), "#app");
